spring:
  datasource:
    url: jdbc:mysql://3.39.176.88:3306/sns
    username: chjeong
    password: c06230731
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-aql: true

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK